[build-system]
requires = ["hatchling", "hatch-odoo"]
build-backend = "hatchling.build"


[project]
name = "oca-custom"
version = "18.0"
description = "OCA France Odoo's instance"
# readme = "README.md"
requires-python = "==3.13.*"
dynamic = ["dependencies"]

[tool.hatch.build]
packages = ["./"]

# Enable the hatch-odoo metadata hook to generate dependencies from addons manifests.
[tool.hatch.metadata.hooks.odoo-addons-dependencies]
# Enable the hatch-odoo build hook to locate the Odoo addons and package them in odoo/addons.
# if not provided, "locals" modules (those in './') are not found and cannot be installed...
[tool.hatch.build.hooks.odoo-addons-dirs]

[tool.hatch-odoo]
# dependencies that are not in the addons manifest
dependencies = [
  "click-odoo-contrib>=1.22",
  "lxml[html_clean]",
  "num2words",
  "pdfminer",
  "phonenumbers",
  "psycopg2-binary==2.9.*",
  "python-slugify[unidecode]",
  "reportlab>=4.1.0",
  "packaging",
  "pypdf2<3",
  "werkzeug==3.0.*",
  "openupgradelib",
  "pygments",                  # to silence Odoo warning which uses pygments for README.rst rendering
  # indirect dependencies with Open PRs needs to be declared explicitly
  # to be installed from git branch
  "odoo-addon-account_statement_import_api==18.0.*",
  "odoo-addon-account_statement_import_api_qonto==18.0.*",
  "odoo-addon-account_statement_import_in_invoice_api==18.0.*",
  "odoo-addon-account_statement_import_in_invoice==18.0.*",
  "odoo-addon-res_company_mastodon_link==18.0.*",
  "odoo-addon-website_social_media_link==18.0.*",
  "odoo-addon-website_membership_non_paid_member==18.0.*",
  "odoo-addon-res_partner_linkedin_link==18.0.*",
  "odoo-addon-res_partner_mastodon_link==18.0.*",
  # Addons that are not declared in manifests because we don't want
  # them installed automatically.
]
addons_dirs = ["./"]

[tool.uv]
# On OCA 14.0 series translations commits are realeased
# in pre-release state
prerelease = "allow"
# tell uv when dependencies may change
cache-keys = [{ file = "pyproject.toml" }, { file = "**/__manifest__.py" }]
# avoid build psycopg on production server
exclude-dependencies = ["psycopg2"]

[dependency-groups]
dev = [
  "odoo==18.0.*",
  "pytest-odoo",
  "pytest-cov",
  "pytest-xdist>=3.6.1",
  "checklog-odoo",
  "manifestoo",
  "freezegun",
]


[tool.uv.sources]
# Use fix updating account move line update membership line
odoo = { git = "https://github.com/OCA/OCB", branch = "18.0" }

# unreleased dependency, add it to test-requirements.txt to let the
# test pipeline to use it as well
odoo-addons-design-themes = { git = "https://github.com/petrus-v/design-themes", branch = "18.0-add-pyproject" }
odoo-addon-account_statement_import_api = { git = "https://github.com/akretion/bank-statement-import-api", branch = "18.0", subdirectory = "account_statement_import_api" }
odoo-addon-account_statement_import_api_qonto = { git = "https://github.com/akretion/bank-statement-import-api", branch = "18.0", subdirectory = "account_statement_import_api_qonto" }
odoo-addon-account_statement_import_in_invoice_api = { git = "https://github.com/akretion/bank-statement-import-api", branch = "18.0", subdirectory = "account_statement_import_in_invoice_api" }
odoo-addon-account_statement_import_in_invoice = { git = "https://github.com/akretion/bank-statement-import-api", branch = "18.0", subdirectory = "account_statement_import_in_invoice" }
odoo-addon-website_social_media_link = { git = "https://github.com/OCA/website", rev = "refs/pull/1170/head", subdirectory = "website_social_media_link" }
odoo-addon-website_company_mastodon_link = { git = "https://github.com/OCA/website", rev = "refs/pull/1141/head", subdirectory = "website_company_mastodon_link" }
odoo-addon-website_membership_non_paid_member = { git = "https://github.com/OCA/vertical-association", rev = "refs/pull/221/head", subdirectory = "website_membership_non_paid_member" }
odoo-addon-res_partner_linkedin_link = { git = "https://github.com/OCA/social", rev = "refs/pull/1869/head", subdirectory = "res_partner_linkedin_link" }
odoo-addon-res_partner_mastodon_link = { git = "https://github.com/OCA/social", rev = "refs/pull/1870/head", subdirectory = "res_partner_mastodon_link" }

# Example to develop module from an other repository
# installing in editable mode
# odoo-addon-membership-delegated-partner-line = { path = "src/vertical-association/setup/membership_delegated_partner_line", editable = true }


[tool.pytest]
addopts = ["-v", "-s", "--cov-report", "term-missing", "--cov", "."]

[tool.coverage.run]
branch = true
omit = [
  "src/*",
  "./*/tests/*",
  "./*/__manifest__.py"
]
